# Generated by Django 5.0.6 on 2024-09-04 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='static/portada', verbose_name='Imagen del libro')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('sinopsis', models.TextField(default='Sinopsis No Disponible')),
                ('editorial', models.CharField(blank=True, max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('cant_paginas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dimension', models.CharField(blank=True, max_length=50, null=True)),
                ('encuadernacion', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('I', 'Indefinido'), ('F', 'Libro Fisico'), ('A', 'Audio Libro'), ('E', 'Ebook')], default='I', max_length=15)),
                ('narrador', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion', models.SmallIntegerField(blank=True, null=True)),
                ('extension_archivo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('correo', models.EmailField(max_length=254)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('N', 'Enviado'), ('D', 'Entregado'), ('C', 'Cancelado')], default='P', max_length=2)),
                ('numero_compra', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_libros', to='Pedidos.pedido')),
            ],
        ),
    ]
