# Generated by Django 5.0.6 on 2024-09-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0002_alter_cart_libro'),
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'P'), ('Enviado', 'N'), ('Entregado', 'D'), ('Cancelado', 'C')], default='Pendiente', max_length=10),
        ),
    ]
