# Generated by Django 5.0.6 on 2024-09-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_delete_libro_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'P'), ('Enviado', 'E'), ('Entregado', 'F'), ('Cancelado', 'C')], default='Pendiente', max_length=10),
        ),
    ]
