# Generated by Django 5.0.6 on 2024-10-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0005_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'permissions': [('can_change_status', 'Can change order status')]},
        ),
    ]
