# Generated by Django 5.0.6 on 2024-12-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0006_alter_pedido_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'P'), ('Enviado', 'E'), ('Entregado', 'Et'), ('Cancelado', 'C')], default='Pendiente', max_length=10),
        ),
    ]
