# Generated by Django 5.0.6 on 2024-09-06 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0001_initial'),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='libro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.libro'),
        ),
    ]
