# Generated by Django 5.0.6 on 2024-10-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_alter_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto_perfil',
        ),
    ]
