# Generated by Django 5.0.6 on 2024-10-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_libro_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'permissions': [('can_change_stock', 'Can change stock of books')]},
        ),
    ]
